### ISSUE TITLE
mumu12，绑定失败，请换个绑定模式

### ISSUE THREAD

**Issue by miaomiaocatmsg** [hliunian/vigilant-invention#1]
![QQ截图20240330192157](https://github.com/hliunian/vigilant-invention/assets/50607849/7fbeb827-c660-43ee-b56c-7488273c6b8a)

rt..

话说有使用说明嘛？

**Comment by hliunian** [comment]
您好，mumu模拟器绑定失败的问题，可以在info.ixi 将533改成000 或者采用雷电模拟器### ****

**Comment by miaomiaocatmsg** [comment]
mumu还是失败~底层是乐玩吗？

乐玩后台键鼠绑定不了mumu12 悲伤的故事

**Comment by hliunian** [comment]
您好，是的，由于是free的项目我们采用底层是乐玩，后续有计划将会开发大漠版本的，如果您还是无法绑定mumu请将您的目录下info.ini内容截图与问题提出新的issues方便我们进行查看&nbsp;


物以是人非
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月31日(星期天) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [hliunian/vigilant-invention] mumu12，绑定失败，请换个绑定模式 (Issue #1)














 
mumu还是失败~底层是乐玩吗？
 
乐玩后台键鼠绑定不了mumu12 悲伤的故事

**Comment by miaomiaocatmsg** [comment]
![image](https://github.com/hliunian/vigilant-invention/assets/50607849/4d17a081-fd61-4031-9edb-d8bb072279f5)

重新下载1.115版本遇到了2个问题
1、版本号不知道是不是没有修改 显示1.114
2、在拖动十字星的时候，又出现问题了，一直闪烁，似乎鼠标放下，这里命令出问题了，导致窗口句柄一直不能确定
3、手动输入窗口句柄，又会显示新的问题，如图
![image](https://github.com/hliunian/vigilant-invention/assets/50607849/c8b00255-ee85-4a2b-bb5e-13cfe82c9b75)
4、是否有交流群可以实时反馈哇~（如果用大漠的话，我可以使用自己的注册码，这样您也不需要额外付费啦）

**Comment by hliunian** [comment]
您好 该项目交流群应该为:995888719
&nbsp;


物以是人非
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月31日(星期天) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [hliunian/vigilant-invention] mumu12，绑定失败，请换个绑定模式 (Issue #1)














 
image.png (view on web)
 
重新下载1.115版本遇到了2个问题
 1、版本号不知道是不是没有修改 显示1.114
 2、在拖动十字星的时候，又出现问题了，一直闪烁，似乎鼠标放下，这里命令出问题了，导致窗口句柄一直不能确定
 3、手动输入窗口句柄，又会显示新的问题，如图
 image.png (view on web)
 4、是否有交流群可以实时反馈哇~（如果用大漠的话，我可以使用自己的注册码，这样您也不需要额外付费啦）
